### ISSUE TITLE
Remove unneeded javascript polyfills

### ISSUE THREAD

**Issue by njam** [cargomedia/CM#1476]
Now that we're [not supporting IE9 anymore](https://github.com/cargomedia/CM/pull/1474) there might be other polyfills that are not needed anymore.

Please check all javascript polyfills and compare with caniuse.com and [supported browsers](https://github.com/cargomedia/sk/wiki/Supported-Browsers)

**Comment by vogdb** [comment]
All of the libraries are finally updated.
