### ISSUE TITLE
Splittest fixture requestClient/user mismatch

### ISSUE THREAD

**Issue by alexispeter** [cargomedia/CM#1571]
Under certain circumstances (User is assigned a fixture A, then switches to a different client which is assigned fixture B) a user's client may be assigned a different fixture than the user himself.

This leads to two problems.
 1. If you alternately use the same splittest based on user and based on client, as done in https://github.com/cargomedia/sk/pull/902, the variations of the feature you want to test will be mixed, depending on which fixture is used, the user's or the client's.
 2. Conversion always uses the user's variation, not the client's. A user may have been assigned variation A while having most of his user experience under variation B, which leads to incorrect conversion.

The number of users affected by this is probably low, since it can only happen if you switch clients, deliberately delete cookies or use a client that doesn't store cookies, e.g. chrome in incognito mode.

Thoughts @njam, @fauvel?

**Comment by njam** [comment]
Makes sense. Some call similar to the existing `setUserForRequestClient()` in `CM_Session::setUser()`.
One concern I have is that we currently never change a variation fixture after it has been assigned. We need to be careful to not have inconsistent data.

@fauvel you have some more thoughts maybe?

**Comment by fauvel** [comment]
I rekon we have developed this together @njam, and I already had the same concerns than @alexispeter. We've opted for this solution *for performance reasons*.

**Comment by fauvel** [comment]
We've also had a look at usage data (number of clients per user, based on GA data if I remember correctly), and considered that this issue was not statistically relevant.

**Comment by njam** [comment]
IMO we ignore it then.

@alexispeter please close if you agree.

**Comment by alexispeter** [comment]
I guess...
