### ISSUE TITLE
Use "runtime" instead of "apc(u)" for local-cache when in CLI mode?

### ISSUE THREAD

**Issue by njam** [cargomedia/CM#1572]
Problem: We experience APC(u) being unstable/problematic in high memory usage situations. Segfaults are usually the result.

Idea: Instead of using the APC-storage for `LocalCache` we could use the Runtime-storage (php array-based).

Possible concerns:
- PHP array storage might use more memory than APC storage. To conclude we should test what's the difference. Also we should determine how much local-cache memory our CLI processes use.

@ppp0 @kris-lab @tomaszdurka wdyt?

**Comment by tomaszdurka** [comment]
You want to use runtime cache instead of apc only for cli, right?
Additionally we do not limit apc max memory within configuration? Or it's segfaulting when hitting it's own limit...?

**Comment by njam** [comment]
> You want to use runtime cache instead of apc only for cli, right?

Yes

> Additionally we do not limit apc max memory within configuration? Or it's segfaulting when hitting it's own limit...?

Do you mean apcu's `apc.shm_size` setting? We set it to [1.5GB here](https://github.com/cargomedia/puppet-cargomedia/blob/e4c3d889e3db3a941a61843d2eb957b432d48c73/modules/cargomedia/files/hiera-data/datacenter/softlayer.json#L4).

**Comment by njam** [comment]
@alexispeter maybe for you? Let me know so we can discuss..

**Comment by alexispeter** [comment]
Would it also be an option to not cache at all in cli-mode? If we're only going to use runtime-cache, a cli process will only hit the cache when accessing entries created by the process itself, which I don't think a lot of tasks do.

**Comment by njam** [comment]
We have quite a few entries in APC that need to be cached even for CLI: Translations, Splittests, Usertext, Classchildren. Some of these are heavy to calculate so we should cache them!

**Comment by njam** [comment]
As discussed please check memory usage for APC and "Array" for ~100MB in ~1000 keys. Based on that we can decide how to proceed.

**Comment by alexispeter** [comment]
##### Memory Usage for 1000 keys à ~0.1MB
**apc:** 145MB
**runtime:**125MB

There is a threshold at ~309MB, starting from which APC will not use more memory for increasing data. Runtime-cache memory usage on the other hand will continue to grow linearly.

**Comment by njam** [comment]
So it looks like "runtime" can store more efficiently even, but of course it doesn't do mmapping. This might be a problem if *lots* of data is put into local cache.

@cargomedia/devops before we proceed I'd like to get everyone's opinion here.
Upside: Not using APC(u), which we found to be sometimes unreliable (segfaults)
Downside: No more mmapping

wdyt?

**Comment by ppp0** [comment]
Any code so that we can test/reproduce your findings? 
what about using an external object cache? I'm thinking of memcache or redis here but there might be other solutions.
Or throw more RAM at the problem?

For a competent opinion I need time to do some research

**Comment by alexispeter** [comment]
I can offer you a branch if you want to test things yourself. Or did you want to test it on production?

**Comment by kris-lab** [comment]
As we discussed @cargomedia/devops this change is not rally trivial, affects strongly app and requires a lot of efforts to find best solution, implement, test it and still we have no guarantee that there will be no more new issues.

I would close it and KEEP IN MIND that the source of segfaults is the APCu!

wdyt?

**Comment by njam** [comment]
Agree, let's revisit if it pops up again.
@alexispeter thanks for the research!
