### ISSUE TITLE
MongoCursorTimeoutException for getConversationsUnread()->getCount()

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/CM#1590]
Read timed out after reading 0 bytes, waited for 30.000000 seconds.

Probably query takes more than 30sec on some circumstances?

cc @alexispeter

**Comment by njam** [comment]
Chris and me added a "slow queries" metrics to bipbip.
We will replace HDD to SSD and see what's the impact.

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/sk/issues/1203
