### ISSUE TITLE
Remove CM_Class_Abstract

### ISSUE THREAD

**Issue by alexispeter** [cargomedia/cm#1629]
##### Motivation

Enable class-configuration capabilities on a class without having to alter it's inheritance. E.g. CM_Paging_Abstract no longer needs to extend CM_Class_Abstract just so a few select children can use class-configuration features.
##### Idea
- introduce `CM_Class_ConfigTrait` to handle class-config logic
- introduce `CM_Class_TypeTrait` to handle class-type logic (will be interwoven with preexisting `CM_Typed` interface)
- move `getClassHierarchy()` into `CM_Util`

**Comment by alexispeter** [comment]
thoughts @njam @tomaszdurka ?

**Comment by njam** [comment]
> Favor composition over inheritance

sgtm! Let's treat it as "slack" though?

**Comment by tomaszdurka** [comment]
I am not sure about the structuring. Probably trait could be more of `CM_Config_ConfigurableTrait`, not sure about the `Typed` though.

**Comment by alexispeter** [comment]
Type is closely tied to the config.

**Comment by alexispeter** [comment]
I prefer to keep the current naming. 
`CM_Config_*` sounds a bit ambiguous, while `CM_Class_*` infers that this applies to the class as such.

**Comment by tomaszdurka** [comment]
Regarding the Config namespace I thought it would be good to put all Config related things there. 

I would still go for:
- `CM_Config_ConfigurableTrait` (maybe along with `CM_Config_ConfigurableInterface`)
- `CM_Config_TypedInterface`

Using adjectives for above is a bit more easier to understand what does object do, @alexispeter agree?

*I've also added interface as suffix, what do you think about having this as convention too?*

**Comment by alexispeter** [comment]
> I've also added interface as suffix, what do you think about having this as convention too?

I already renamed `CM_Typed` to `CM_Class_TypeInterface` in my branch ;)

> Using adjectives for above is a bit more easier to understand what does object do, @alexispeter agree?

Agree to do this where applicable (don't invent new words).

Regarding which module to put it in, I still advocate CM_Class_* as those traits are only related to the Config in that they use it, but they are more closely tied to the concept of "classes". I mean we also call the mongodb storageadapter `CM_Model_StorageAdapter_MongoDb` and not `CM_MongoDb_ModelStorageAdapter` just because it uses mongodb.

**Comment by alexispeter** [comment]
Then again, maybe introducing a new module just for those traits doesn't make much sense.

**Comment by alexispeter** [comment]
Since these changes are very extensive, I will deprecate `CM_Class_Abstract` instead of removing it entirely and apply changes in small portions.

**Comment by alexispeter** [comment]
Functionality in CM_Class_Abstract can be divided into configuration- and structure-related methods.

##### Configuration #####
- getType()
- getTypeStatic()
- _getClassName()
- _getConfig()
- _getConfigRaw()
##### Class Structure #####
- getClassHierarchy()
- getClassChildren()
- _getClassHierarchy()
- _getClassNamespace()

How about introducing services for both? Class stuff could also go to CM_Util if a service is overkill.

**Comment by njam** [comment]
As discussed let's extract these two functionalities into separate classes/modules, but not services just yet. We can then expose them through traits, and with `CM_Class_Abstract` as a temporary solution until code is refactored.
