### ISSUE TITLE
Catch `CM_Class_Exception_TypeNotConfiguredException` and re-throw as `CM_Exception_Nonexistent`

### ISSUE THREAD

**Issue by dlondero** [cargomedia/CM#1635]
In `CM_Http_Request_Abstract::popPathSite()` catch  `CM_Class_Exception_TypeNotConfiguredException` and re-throw as `CM_Exception_Nonexistent` because passing a wrong language or site-id in the URL should lead to 404.

**Comment by dlondero** [comment]
@njam unfortunately it's not as easy as it seems because `CM_Exception_Nonexistent` it treated as a 404 at the `page` level and in this specific case we're not there. Checked this with @tomaszdurka and the refactoring looks quite big if we think to move `CM_Exception_Nonexistent` and `CM_Exception_InvalidParam` to higher level.

**Comment by njam** [comment]
Hm I see. I got alerted tonight 5:30 so I'm still in favor of making this a non-error ;)

Example problematic URLs:
- `/ajax/de-de/100`
- `/layout/de-de/100/1423665456/manifest.json`
The language is not detected, so `de-de` is treated as the *site-id*.

Looking a bit at the whole Request/Response classes, I think the following should be done:
- Request should not *change*, especially not by other classes -> #1636
- The `popSomething()` functions should be changed to `getPathPart($index)`, so they only return a value, and don't have side-effects on the Request.
 - Then the Response would get the relevant parts from the Request in its `_process()` method.

@dlondero @tomaszdurka wdyt?

**Comment by tomaszdurka** [comment]
Maybe that is not bad solution. As I understand you would non-obtrusively check if request matches any response and if not proceed to other response. Still it throw some kind of bad url exception if none response matched - which would be presented as `Not Found`. I definitely agree it would be good to not alter Request in the whole process.

It will still require some app logic to verify request is correct - like check if site with given id really exists.

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/CM/pull/1638
