### ISSUE TITLE
manifest.json (Chrome) not loading from cross-domain location

### ISSUE THREAD

**Issue by njam** [cargomedia/CM#1712]
E.g. www.denkmal.org has the following *link* tag:
```html
<link rel="manifest" href="http://cdn.denkmal.org/layout/de/35/1427044499/manifest.json">
```

That `manifest.json` is never loaded by Chrome. If the domain in the `href` is changed to `www.denkmal.org` it *is* loaded.

[W3C spec](http://www.w3.org/TR/appmanifest/) seems to allow CORS (6.1.1 Content security policy), and we set the appropriate headers in `CM_Http_Response_Resource_Abstract`.

@christopheschwyzer @vogdb  @cargomedia/devops  ideas, thoughts?

**Comment by ppp0** [comment]
Are you sure you are setting the header right? If I inspect the request/response of http://cdn.denkmal.org/layout/de/35/1427044499/manifest.json I get:

```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx
Date: Thu, 02 Apr 2015 09:45:08 GMT
Access-Control-Allow-Origin: http://www.denkmal.org
Expires: Fri, 01 Apr 2016 09:45:08 GMT
Cache-Control: max-age=31536000
Content-Encoding: gzip
Age: 2493
X-Cache: Hit from cloudfront
[...]
```

**Comment by njam** [comment]
What is it that looks wrong - there is `Access-Control-Allow-Origin`?

**Comment by ppp0** [comment]
yes, but allowing `http://www.denkmal.org` not `cdn.denkmal.org`? Did I get wrong what the problem is?

**Comment by njam** [comment]
I think that's correct, as the file is on `cdn.denkmal.org` but included in the website at `www.denkmal.org`. See http://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

One thought (which I didn't verify yet), is that the browser issues an `OPTIONS` request which we don't support?

**Comment by ppp0** [comment]
See https://w3c.github.io/manifest/ Section 2.1 / Note - Suggests that the `manifest.json` is not suitable to be cached by a CDN?

**Comment by njam** [comment]
Hmm, you're right, but what about 6.1.1?

2.1:
> Please also note that manifest's URL has to be same origin, so you can't use them directly with a CDN.

6.1.1:
> Remote origins (e.g., a CDN) wanting to host manifests for various web applications will need to include the appropriate [CORS] response header in their HTTP response (e.g., Access-Control-Allow-Origin: https://example.com).

Weird.

**Comment by njam** [comment]
Now serving from same hostname.
