### ISSUE TITLE
Check problems with forking while Redis client active

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#1728]

**Comment by njam** [comment]
Possibly fixed by https://github.com/cargomedia/cm/pull/1923
cc @zazabe

**Comment by njam** [comment]
@zazabe fixed by https://github.com/cargomedia/cm/pull/1923? wanna check?

**Comment by zazabe** [comment]
@njam same comment than for https://github.com/cargomedia/cm/issues/1920#issuecomment-144646838, i suppose it's fixed.

**Comment by njam** [comment]
@tomaszdurka can you elaborate what the original problem was? Do you know how to reproduce?

**Comment by njam** [comment]
Tomasz cannot remember, we'll close for now.
