### ISSUE TITLE
Only enable split tests for new users

### ISSUE THREAD

**Issue by njam** [cargomedia/CM#1735]
First version: #1729
Reverted: #1734

> The other way round, it works like that: A new visitor (e.g. deleted cookies) signs in as an old user. He will see a given LP variation, then we'll store the userId upon sign up and assign it to the request client fixture, so that conversions get tracked properly.

> So it's basically as it was before... difficult to filter out these cases.

> hm, we could do a check in "setUserForRequestClient()"?
> and retrospectively delete client-fixtures if we notice they belong to an old user?

**Comment by fauvel** [comment]
@njam I remember we've implemented a simplified, and not completely correct version of `setUserForRequestClient()` a few years (?) ago, for performance reasons. I guess we're going to run into the same kind of issues here... I'm not sure about it yet, but we'll have to keep it in mind.

**Comment by njam** [comment]
Hmm but that function is only called on `CM_Session::setUser()` (mainly login).
The last change to that function I can find is: https://github.com/cargomedia/CM/pull/509

**Comment by NicolasSchmutz** [comment]
@fauvel @eillasti should we close this, as we're doing this in RJM usually?

**Comment by eillasti** [comment]
I would not implement this, because sometimes we also want to include the old users, so it is better to put this filter on the analytics end.
