### ISSUE TITLE
wowza: scalabilty

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/cm#1749]
Part of https://github.com/cargomedia/roadmap/issues/15

- [ ] AWS CloudFormation support
 - [ ] runtime storage for running `formations`/`farms` of servers
 - [ ] start/create `formation` from template
 - [ ] monitor `farms`
 - [ ] destroy `farms`
- [ ] CM/Wowza - load monitoring for video streams
 - [ ] detecting publishers load
 - [ ] detecting subscribers load per show
- [ ] dynamic server configuration for `service-manager` and `app-configuration`
- [ ] dynamic video stream services
 - [ ] get new `publisher stream name` based on specific `wowza cloud formation`
 - [ ] `background-job` which starts new CloudFormations before load will appear (schedule)

To discuss:
- [ ] make it possible to run as separate service which would be used by fuboo/sk?
 - [ ] simple API which would provide "stream names" for providers
 - [ ] simple API which could schedule events

**Comment by kris-lab** [comment]
Draft of wowza scalability approaches

![scaling - new page 2](https://cloud.githubusercontent.com/assets/1843523/7365722/2f339640-ed93-11e4-8397-fcf169a9c5d5.png)

@njam @tomaszdurka a few initial thought about wowza scaling approaches

**Comment by njam** [comment]
So you confirmed the second approach is possible?, with:
- Using "load balancer" on publisher's end
- Connecting "edge" servers to multiple "engines"

Alternatively as discussed we could multiply the first schema ("per event"), and register all of these clusters in CM, which supports [round robin](https://github.com/cargomedia/CM/blob/52e85c55c27db07f2db97b02db77ab38c963b4a0/library/CM/Stream/Video.php#L39) for multiple servers.

**Comment by kris-lab** [comment]
Well, there are options which I am testing and evolving now...

> Using "load balancer" on publisher's end

I will confirm one more time but I don't see any downside for doing this. It is kind of basic behaviour of balancing. Wowza balancer works similar to `round robin` with extension to measure load on end-points.

> Connecting "edge" servers to multiple "engines"
afaics it is impossible to do it easy. There is option that every `wowza engine / publisher` could have another application name so `wowza edge` instances could bind to all of them. The downside are restarts of `edge` instances every time the `publisher` instance come up. Also this approach require some advanced `CM` logic for controlling.

`Per Event Scaling` feels less complicated and better scalable but it is not my final point of view:)

**Comment by kris-lab** [comment]
@tomaszdurka please have a look on updated "head comment" and [abstract requirements for CM app](https://cloud.githubusercontent.com/assets/1843523/7510268/89cf8326-f49a-11e4-834a-b69c1edacc0e.png)

@tomaszdurka [cloud formation could be done as separate service/api](https://cloud.githubusercontent.com/assets/1843523/7510285/c5a2cfca-f49a-11e4-8743-03460e80fba9.png)

let's pair on it a bit? and discuss on stand-up

**Comment by njam** [comment]
Did you consider using Terraform instead of CloudFormation?

**Comment by kris-lab** [comment]
I didn't think about Terraform but in this case it could make sense. I will have to investigate. 

AWS/SDK/CloudFormation is pretty robust I would say but Terraform sounds exciting:)

**Comment by njam** [comment]
As discussed the following might be a good solution:
- Terraform to define and deploy infrastructure "bundles"
- Ansible to run Terraform "apply"
- [Ansible Tower](http://www.ansible.com/tower) to trigger and control Ansible tasks. Can be accessed via REST API (similar to pulsar-rest-api).

**Comment by kris-lab** [comment]
:+1: Agree, this is very good replacement of `CM_AWSCloudFormation_*` which would limit us in the future.

Still the question is should we build this stuff as separate service/api :)?

**Comment by njam** [comment]
The *ansible tower* could run on a dedicated cargomedia-wide machine, which provides a REST API to launch and control infrastructure. The application could then just have a job to trigger some `launch-new-sk-wowza-publisher` task on that API.

**Comment by kris-lab** [comment]
so then:
- where would you store the runtime configuration to measure the load (number of publishers) on the specific `server-group` and also to store IPs, channelName etc?
- how would you centralised authentication RPC calls (single point on www3 or any in App farm)?

**Comment by njam** [comment]
- Runtime wowza publisher config: Currently stored in flat config file. But the whole implementation allows for multiple wowza servers. We would just need to move parts of this configuration into mysql, shouldn't be too hard.
- RPC: Currently go to `https://www.fuckbook.com/rpc/null`, so load balanced by the HTTP proxy. Could stay as is

**Comment by kris-lab** [comment]
- I meant rather that if we start new `group of servers` then each `streamName` would be assigned exactly to one `group of servers`? We need layer which could detect where the `streamName` belongs to? Just to provide some informations for subscribers etc? I assume that each `group` has own load balancer etc.
- agree

**Comment by njam** [comment]
That mechanism is mostly built-in afaik. If you look at `CM_Stream_Adapter_Video_Wowza::synchronize()`, you can see that status information is enriched with server hostname:
```php
$publish['serverHost'] = $wowzaServer['privateIp'];
```

And on the publisher side (`SK_Component_VideoStreamPublish`) we use `CM_Stream_Video::getServer()` which picks a random server to publish to:
```php
        if (null === $serverId) {
            $serverId = array_rand($servers);
        }
```

**Comment by kris-lab** [comment]
Just draft of concept for the records [cm-ansible-teraform-aws-puppet](https://cloud.githubusercontent.com/assets/1843523/7513174/665f2de8-f4b2-11e4-8ec8-4c8925662506.png)

**Comment by njam** [comment]
Depending on how complex that `terraform apply` command to launch a new *wowza publisher* is we could also just use *pulsar* and *pulsar-rest-api*!

**Comment by kris-lab** [comment]
Hmm I did some test already and I believe we could do it with `pulsar-rest-api` and pulsar tasks.

Would work:
- at least `terraform apply` by defining `pulsar task`

Not sure:
- about e.g `terraform output ip` etc. to get runtime configuration; how to do it easily via `pulsar-rest-api`?
- also where to store the `*.tf` files; CM or pulsar-conf-cargomedia?

**Comment by njam** [comment]
Regarding pulsar-rest-api: You can either call the job "blocking", then the result will be returned, or can use "non-blocking" and use WebSocket to retrieve result.
See: https://github.com/cargomedia/pulsar-rest-api#create-job

Not sure about TF-files either :)

**Comment by kris-lab** [comment]
Ahh I see, we have `blocking` requests to `pulsar-rest-api`; very cool!

**Comment by NicolasSchmutz** [comment]
Closing for the time being. Pleas reopen if you disagree.
