### ISSUE TITLE
Introduce CM_Image_Definition to combine "dimensions", "format", "square"

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#1843]
Via https://github.com/cargomedia/CM/pull/1667

To simplify defining of types of images.
For example in the photo entity we can then have a _Definition_ per type:

``` php
    /**
     * @param string $type
     * @return CM_Image_Definition
     */
    public function getImageDefinition($type) {
        $format = $this->getImageFormat($type);
        $imageDefinitionList = [
            self::TYPE_VIEW => new CM_Image_Definition(width = 900, height = 900, square = false, format = $format),
            self::TYPE_THUMB => new CM_Image_Definition(width = 100, height = 100, square = true, format = $format),
        ];
        return $imageDefinitionList[$type];
    }
```

And use it when writing a new image to files:

``` php
    /**
     * @param CM_Image_Image $imageOriginal
     */
    public function writeCopies(CM_Image_Image $imageOriginal){
        foreach (self::$TYPE_LIST as $type) {
            $imageDefinition = $this->getImageDefinition($type);
            $image = $imageDefinition->apply($imageOriginal->getClone());
            $this->getFile($type)->write($image->getBlob();
        }
    }
```

Paired with @alexispeter
@tomaszdurka thoughts?

**Comment by tomaszdurka** [comment]
Looks good. Maybe we should introduce additionall classes for each size though? Or some collection class? I don't like those constants so much.

**Comment by alexispeter** [comment]
I thought about this some more and am a bit sceptical in that this specification is much too specific to our needs to be in CM. What we need is a way that allows us to define a sequence of operations on an image. I think the effort would be too great compared to the benefit we would reap off of a flexible solution.

Unless we define this as being tailored directly to "shrinking" images and nothing else.

**Comment by njam** [comment]
I thought that the "Definition" thing is more like a *should be* state of certain image attributes, and not a set of specific instructions of how to get to that state. This way it allows to find the optimal set of instructions to get the image from the *is* to the *should* state.
Maybe there could still additionally be a concept of "sequence of operations", but I think it should be *additionally* to the "definition" concept.
@tomaszdurka @alexispeter wdyt?

**Comment by alexispeter** [comment]
What I don't like is that for certain attributes, the specified should-value can be attained with different operations that have completely different results, but let's just do it.

**Comment by njam** [comment]
You mean like whether to first crop and then resize, or first resize and then crop? Which can lead to different quality levels?

**Comment by njam** [comment]
Closing for now
