### ISSUE TITLE
Extend FormFields: Range Slider

### ISSUE THREAD

**Issue by christopheschwyzer** [cargomedia/cm#1887]
@njam / @tomaszdurka 
> Range slider with two handles (min and max value selection)

Should we introduce something like `CM_FormField_Range` or `CM_FormField_Integer_Range` - Idea is to have two handles for _min_ and _max_ values for e.g. age selection. 

Also, I think the default integer form field should be a simple text input (maybe with a pattern restriction http://caniuse.com/#feat=input-pattern), the slider should be an optional  _theme_ / _template_

wdyt?

**Comment by njam** [comment]
Generally sounds reasonable.
What will the two-value range slider be used for?

**Comment by christopheschwyzer** [comment]
> e.g. age selection

**Comment by njam** [comment]
Makes sense. I'm wondering if it's working nicely though, with two sliders. Never saw it in the wild.. but maybe I'm browsing the wrong sites?

**Comment by christopheschwyzer** [comment]
http://refreshless.com/nouislider/

We already use this plugin for _Integer_. I think it's should be doable for _Range_.
