### ISSUE TITLE
Scroll position restoration for history API

### ISSUE THREAD

**Issue by vogdb** [cargomedia/cm#1898]
https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration

**Comment by njam** [comment]
Related to https://github.com/cargomedia/cm/pull/760
cc @alexispeter

**Comment by njam** [comment]
Browser support is okay: https://github.com/Fyrd/caniuse/issues/1889

**Comment by vogdb** [comment]
what about WebKIT? The link that is given there leads to the issue that is still opened.

**Comment by njam** [comment]
It seems available in Chrome and Firefox only. Would still be good to set it (as we *are* restoring scroll position manually, see https://github.com/cargomedia/cm/pull/760).

**Comment by njam** [comment]
let's close it for now
