### ISSUE TITLE
CM_Elasticsearch_Cluster: Use 1 Client with multiple servers

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#1905]
Currently our elasticsearch cluster creates a `Elastica\Client` instance for each configured server:
```php
    public function __construct(array $servers, $disabled = null) {
        $this->setEnabled(!$disabled);
        foreach ($servers as $server) {
            $config = array_merge($server, ['timeout' => 10]);
            $this->_clients[] = new Elastica\Client($config);
        }
    }
```
...and then picks one randomly for querying.

This doesn't provide any failover functionality. Shouldn't we rather have 1 `Elastica\Client` with multiple servers configured, so `Elastica\Client` would then do the failover?

@fvovan wanna look into this?
cc @tomaszdurka

**Comment by njam** [comment]
@fvovan is this solved by https://github.com/cargomedia/cm/pull/1906?

**Comment by fvovan** [comment]
Yes, now it has only 1 client with several connections

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/cm/pull/1906 then
