### ISSUE TITLE
Use different internal/external types in model schemas

### ISSUE THREAD

**Issue by alexispeter** [cargomedia/cm#1930]
Use-case:  property in a simpleModel that uses a different datatype in the application than in the storage-system.

Particular problem: a container-entity implemented as simpleModel using mongodb that uses a field `conversation` to  reference a conversation that is stored in mongoDb. The conversation's id is an ObjectId to the storage-layer but a string to the application-layer. Currently our simpleModel approach allows only the id to be an ObjectId, while properties are limited to what is specified in CM_Model_Schema_Definition, which results in the conversationId being stored as string instead of as ObjectId. 
In addition to taking up only half the space of a string of the same length, ObjectIds also offer advantages in querying and sorting performance.

I would like to propose a new field to be added to the schema which lets one define a callback-function to transform a schema-value to it's internal datatype.

```php
protected function _getSchema() {
    return new CM_Model_Schema_Definition(['user'         => ['type' => 'SK_User'],
                                           'conversation' => [
                                               'type' => 'SK_Conversation',
                                               'internalType' => function($conversationId) {
                                                   return new MongoId($conversationId);
                                               })],
    ]);
}
```

thoughts @tomaszdurka @njam

**Comment by njam** [comment]
Doesn't the application usually access the *conversation object* rather (`getConversation()`)?
What are use cases to access the lower level ID, specifically a `MongoId`?

**Comment by alexispeter** [comment]
There are none, it's just the storage-adapter that should know about the internal type.

**Comment by tomaszdurka** [comment]
What about rather getting persistence of the model and using it to parse id accordingly?

**Comment by tomaszdurka** [comment]
Proposed soluton would lead to depndency between model internals and using model in other model's schema. 
- Once you change persistence you need to adjust all the schemas using it.

**Comment by alexispeter** [comment]
> Proposed soluton would lead to depndency between model internals and using model in other model's schema. 
- Once you change persistence you need to adjust all the schemas using it.

On the contrary, it would remove this exact dependency which already exists. 
The only dependency would exist between the referencing model and it's own schema.

**Comment by alexispeter** [comment]
What I want is for the referencing model to be able to store the referenced model in the way it wants, instead of the way the referenced model defines itself.
