### ISSUE TITLE
Replace jQuery with Zepto?

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#1950]
@christopheschwyzer @vogdb 

Since we don't support IE9 anymore, we could consider replacing jQuery with the lightweight Zepto:
http://zeptojs.com/#browsers

This could result in performance improvements (smaller script), but we'd need to check compatibility thoroughly!

**Comment by christopheschwyzer** [comment]
Honestly, I'm not sure it's worth doing. I agree, we can probably save a few `kb`, but it comes with the cost to test / adjust every plugin we use, we need to check all cm based projects, probably refactor some code, plus, jQuery has definitely the bigger community involved which makes it more bug/future-proof.

**Comment by njam** [comment]
agree
