### ISSUE TITLE
Refactor resource Responses and Assets

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm#1971]
Related: https://github.com/cargomedia/cm/pull/1557

ideas:
- Always configure assets via constructor (dont pass config to `get()`)
- Pass "debug" flag to constructor, to decide about "minify", "generateSourceMap" etc?

**Comment by njam** [comment]
@tomaszdurka @alexispeter fyi

**Comment by tomaszdurka** [comment]
Done by @njam
