### ISSUE TITLE
Use source maps on CM assets

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm#1974]
## For JS
- [x] some work has been done for CommonJS  libraries located in `before/after-body-source` with `browserify`, see #1972.
- [ ] generate source maps for all CM javascript files https://github.com/cargomedia/cm/pull/2274
- [ ] generate source maps for vendor libraries (not sure if it's worth it)

[Uglify.js](https://github.com/mishoo/UglifyJS2) is able to achieve this, but there's no option to inline the source map inside the generated file, otherwise we can use nodejs code to do it with something like this:

``` js
#!/usr/bin/env node

var uglify = require('/usr/lib/node_modules/uglify-js');
var args = process.argv.slice(2);
var sourcemap = '--sourcemap' == args[0];
if(sourcemap){
  args = args.slice(1);
}

var result = uglify.minify(args, {outSourceMap: "out.js.map"});

console.log(result.code);
if(sourcemap){
console.log('//# sourceMappingURL=data:application/json;charset:utf-8;base64,' + new Buffer(result.map).toString('base64'));
}
```
## For CSS

Still need to investigate, [LESS](http://lesscss.org/usage/#v2-upgrade-guide-sourcemaps) should be able to help on that...

**Comment by njam** [comment]
…maybe also combine all vendor javascript (find an easy way to require-ify the existing libs)?

**Comment by zazabe** [comment]
maybe something like [exposify](https://github.com/thlorenz/exposify) could help.

**Comment by zazabe** [comment]
will be supported by https://github.com/cargomedia/cm-bundler
