### ISSUE TITLE
Store "requestClientId" for janus subscribe and publish streams

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2031]
The new ViewSession concept has "userId" and "clientId" fields.
To unambiguously identifying a ViewSession in a streamChannel's `onSubscribe()` callback we therefore need those two fields stored in the `cm_stream_subscribe` table. Basically a stream is not only associated to a user, but also to a client (cookie). Because each browser/client can have a different session running.

Idea as discussed with Alexis:
- Introduce an optional `requestClientId` (or more general `uniqueId`?) field for both `cm_stream_subscribe` and `cm_stream_publish`
- Allow to pass the field with `rpc_subscribe` and `rpc_publish` in `CM_Janus_RpcEndpoints`
 - Store it with the subscribe/publish entry
- Pass the field from the client (JS) - Michel can do it

@fvovan @alexispeter @tomaszdurka @zazabe any additional thoughts?

**Comment by fvovan** [comment]
Do we really need it for `cm_stream_publish`, afaiu in that case `requestClientId` should be the publisher, right?
What if we name it `clientId `?

**Comment by njam** [comment]
Theoretically on the level of abstract streamChannels there could be multiple publishers per channel (e.g. video conferencing, or audio room). In that case it could be that the same user account publishes to the same channel twice, from different clients. So the `userId` will be the same, while the  `requestClientId` will be different.

…hm on second thought. The `requestClientId` is also not unique in this case. You can have multiple tabs open with the same `requestClientId`.

**Comment by njam** [comment]
Another idea: Maybe call the field `uniqueId` which would be an optional string field.

Then we could use it and pass the "request client id", but also other IDs like a "websocket stream key".

**Comment by tomaszdurka** [comment]
Not valid anymore.
