### ISSUE TITLE
View: Collect childrenEvents recursively

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2042]
Similar like we do it for `events` (see `CM_View_Abstract.collectEvents()`).

@zazabe @vogdb

**Comment by zazabe** [comment]
we can maybe implement some kind of [callback stack](https://github.com/zazabe/sk/commit/ec47695cd59f0b96851e92c0ba7f4a07ea13dd52)?
Is it good to implicitly call handlers on the child and all his parents? not sure...

@njam @vogdb wdyt?

**Comment by njam** [comment]
True, maybe just collect all event names in the inheritance, but only call the lowest level of each name?

**Comment by vogdb** [comment]
I would rather post here a short example

```js
var SK_Component_Ancestor = SK_Component_Abstract.extend({
  childrenEvents: {
    'SK_Component_SomeNotDescendantChild ready': function(){
      console.log('Should I be executed when Component_Descendant is present?');
      this.toggleBoolean();
    }
  },

  toggleBoolean: function(){
    this._boolean = !this._boolean;
  }
})

var SK_Component_Descendant = SK_Component_Ancestor.extend({
  childrenEvents: {
    'SK_Component_SomeNotDescendantChild ready': function(){
      console.log('I should be executed when I am present');
    }
  },

  toggleBoolean: function(){
    this._super.call();
    this.$el.addClass('boolean--' + this._boolean);
  }
})
```

**Comment by njam** [comment]
@vogdb maybe for you?

**Comment by vogdb** [comment]
As discussed with Michel. This shouldn't be implemented cause Descendant will not be able to cancel `childrenEvents` of Ancestor.
