### ISSUE TITLE
Check our <head>

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2132]
https://github.com/joshbuchea/HEAD

Make sure we have the relevant parts in our `<head>`:
https://github.com/cargomedia/cm/blob/master/layout/default/Layout/Abstract/default.tpl#L4

@christopheschwyzer @vogdb

**Comment by christopheschwyzer** [comment]
Nice repo

**Comment by ppp0** [comment]
Others would have named it "awesome-head"

**Comment by christopheschwyzer** [comment]
Todo:
- Check/Update favicon sizes 
- Check if _Microsoft_ specific meta make sense: 
 ```
<meta http-equiv="cleartype" content="on">
<meta name="skype_toolbar" content="skype_toolbar_parser_compatible">
```

- Update _Chrome_ manifest  (+ splash screen icons) https://developers.google.com/web/updates/2015/10/splashscreen?hl=en
- Safari: Pinned Site `<link rel="mask-icon" href="icon.svg" color="red">`
- There are a lot of optional meta tags https://github.com/joshbuchea/HEAD#meta-element - Don't think they are very useful - but I'm no SEO expert.

**Comment by njam** [comment]
> There are a lot of optional meta tags […] - Don't think they are very useful - but I'm no SEO expert.

Usually not needed I think.

**Comment by christopheschwyzer** [comment]
I am a biit confused about the splash screens. Looks like _Chrome_ uses the icons combined with a background-color defined in the manifest: https://developers.google.com/web/updates/2015/10/splashscreen?hl=en 
Mozilla's manifest suggest `splash_screens_ definitions in the manifest: https://developer.mozilla.org/en-US/docs/Web/Manifest. 

Will stick to the _Chrome's_ (working) guidelines for now. (adding larger versions of the "icon")

**Comment by njam** [comment]
Oh, wanna merge in this one? https://github.com/cargomedia/cm/pull/1977
I've streamlined it with official docu once.

**Comment by christopheschwyzer** [comment]
Closing in favor of #1977.
