### ISSUE TITLE
META: Add timezone support

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2148]
Goals:
- JS: Store timezone offset in a cookie #2150 
- Pass that timezone to the `CM_Frontend_Environment`
 - 1: Look it from the request's cookie #2151 
 - 2: Detect it by finding the closest timezone of the environment's location #2153
 - 3: Take it from the Bootloader/Application

**Comment by fvovan** [comment]
I think it can be closed because everything is merged.
