### ISSUE TITLE
Log ajax response errors on backend before sending them

### ISSUE THREAD

**Issue by fvovan** [cargomedia/cm#2172]
in `CM_Http_Response_View_Abstract::_process()`
It's hard to understand what's going using only `JsException` on because `getMessagePublic()` is not informative enough.

**Comment by njam** [comment]
For what kind of requests?
Are you aware that AJAX errors are logged to the console in dev?
<img width="964" alt="screen shot 2016-05-22 at 17 25 26" src="https://cloud.githubusercontent.com/assets/360800/15454787/493fc954-2042-11e6-9652-76984fceabbb.png">

**Comment by tomaszdurka** [comment]
@fvovan can you elaborate on this? Still valid?

**Comment by fvovan** [comment]
Probably it's not valid anymore.
The thing was i received unclear error messages during development,  and it was quite hard to definitely understand the reason without inserting additional logging.
But I don't exactly remember what errors were in particular and had no success trying to reproduce it.
Can be closed, and i will reponen it if it's needed.
