### ISSUE TITLE
New Relic receiving exceptions that are below the log handler's "minLevel"

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2203]
The new relic log handler should only log errors that are of level ERROR or above (see [config/default.php](https://github.com/cargomedia/cm/blob/master/resources/config/default.php#L255)).
But [New Relic error analytics](https://rpm.newrelic.com/accounts/350429/applications/2137721/filterable_errors) is also showing exceptions that are warnings.

Example: `CM_Http_Request_Post::getQuery()`:
```php
throw new CM_Exception_Invalid('Cannot extract query from body `' . $this->getBody() . '`.', CM_Exception::WARN);
```

@fauvel @fvovan can you investigate?

cc @kris-lab

**Comment by njam** [comment]
As discussed this might be because our exceptions reach the global exception handler.
So could be solved by https://github.com/cargomedia/cm/pull/2146
cc @tomaszdurka

**Comment by fvovan** [comment]
probably it's not related to the topic, but 
I have a suggestion regarding NR handler, 
What if we exclude it from handlers list by default?
the thing is, since it presents on dev environment but never actually sends any data, all mongo handler's exceptions go to nowhere (because backup handler believes that record was processed correctly) what is not convenient. 
Another way is checking if NR is enabled in `CMService_NewRelic_Log_Handler->isHandling()`

@njam, @tomaszdurka wdyt?

**Comment by fauvel** [comment]
Sgtm! Let's make `CMService_Newrelic::_getEnabled` public and add a check in `CMService_NewRelic_Log_Handler::isHandling`, like this?
```php
class CMService_NewRelic_Log_Handler extends CM_Log_Handler_Abstract {

    public function isHandling(CM_Log_Record $record) {
        if (!CM_Service_Manager::getInstance()->getNewrelic()->getEnabled()) {
            return false;
        }
        if (!$record->getContext()->getException()) {
            return false;
        }
        return parent::isHandling($record);
    }

    protected function _writeRecord(CM_Log_Record $record) {
        $newRelic = CM_Service_Manager::getInstance()->getNewrelic();
        $newRelic->setNoticeError($record->getContext()->getException());
    }
}
```

**Comment by fauvel** [comment]
@fvovan @njam @tomaszdurka agree?

**Comment by fvovan** [comment]
oh. It was merged in another here https://github.com/cargomedia/cm/pull/2222

**Comment by fauvel** [comment]
ok lgtm!

**Comment by fvovan** [comment]
@njam, is it closable?

**Comment by njam** [comment]
Yes!
