### ISSUE TITLE
Allow to bind delayed jobs in CM_EventHandler_EventHandler

### ISSUE THREAD

**Issue by dlondero** [cargomedia/cm#2224]
@njam in order to bind delayed jobs to events we need to:
- introduce a `bindDelayedJob` method or 
- at least pass a `$seconds` optional param to `bindJob` and based on that `queue` or `queueDelayed` I'd prefer the first option. Wdyt?

**Comment by njam** [comment]
How about just using plain `bind()` and do it explicitly?:
```php
        $eventHandler->bind('foo', function() {
            $job = new CM_Jobdistribution_Job_Noop();
            $job->queueDelayed(3600);
        });
```

**Comment by dlondero** [comment]
Works as well. Was more to have the same approach for both types of jobs. Closing this anyway.
