### ISSUE TITLE
Warning: "Cannot extract query from body"

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2231]
CM_Http_Request_Post:
```php
throw new CM_Exception_Invalid('Cannot extract query from body `' . $this->getBody() . '`.', CM_Exception::WARN);
```

There's a big increase of those visible in New Relic:
![screen shot 2016-06-28 at 08 35 17](https://cloud.githubusercontent.com/assets/360800/16405910/4bc19a14-3d0b-11e6-9319-18fcffeb9596.png)

But not in our admin (and not in loggly):
![screen shot 2016-06-28 at 08 35 41](https://cloud.githubusercontent.com/assets/360800/16405919/541c2224-3d0b-11e6-9cf2-43308d0b8612.png)

All records' bodies include non-ascii characters in the exception message.
Might be related to the json_encode issue we have: https://github.com/cargomedia/cm/issues/2221

@fvovan can you investigate? Can we see the encoding error?
cc @tomaszdurka 

Could you open another PR and remove the variable from the exception message? Maybe go through all messages, and make sure they don't contain variables?

Related: https://github.com/cargomedia/cm/issues/2235

**Comment by fvovan** [comment]
we currently can't see wrong symbol.
suspicious strings like `***bäke` are already converted before printing to NR.
btw  it's always one of 3 logins.
Would be better to deploy the json changes and track if they get to our Admin with sanitized values.

but i'm wondering why mongo and fluentd logger exceptions didn't reach NR. can you check `error.log` file? (may be if it's not really big it could be sent via email?)

**Comment by fvovan** [comment]
@njam could you run 
`db.cm_log.find({level: 300, createdAt : {$gt : ISODate("2016-07-01T13:00:00Z")} , "context.exception.message" : "Cannot extract query from body"}, {"context.exception.meta" : 1} )`  please ?

**Comment by fvovan** [comment]
closed in favour of https://github.com/cargomedia/cm/issues/2235
