### ISSUE TITLE
New socket-redis client

### ISSUE THREAD

**Issue by vogdb** [cargomedia/cm#2276]
cargomedia/socket-redis#57 brings some breaking changes that require:
- Change `CM_MessageStream_Adapter_SocketRedis`
  
  ``` js
  initialize: function(options) {
    this._socketRedis = new SocketRedis(options.sockjsUrl);
    this._socketRedis.open();
  },
  ```
- Move `socket-redis` directory after `sockjs` directory. Otherwise `window.SockJS` is `undefined` when `socket-redis` is executed.

cc @tomaszdurka

**Comment by vogdb** [comment]
@christopheschwyzer @njam I need to put the directory `client-vendor/after-body/socket-redis` after `client-vendor/after-body/sockjs`. What is more preferable solution? Rename `client-vendor/after-body/sockjs` to `client-vendor/after-body/50-sockjs`?

I need such order cause `socket-redis` with release 3.0.0 will be executed inline and it requires a global variable `SockJS` which is not available cause `sockjs` is located/executed after `socket-redis`.

**Comment by njam** [comment]
Could we use proper `export`/`require` instead?
And then add an entry point to the `after-body-main/socket-redis.js` which would expose what's needed on the global context?

**Comment by zazabe** [comment]
as discussed with @vogdb, I would rather bundle `sockjs-client` and the `socket-redis` client together manually with browserify, and then add the result into `after-body`.
Adding `socket-redis` repo + all his dependencies (`sockjs-client`,...) in `sources` will be huge, and I don't think it's worth it.

**Comment by vogdb** [comment]
Waiting on socket-redis@3.0.0

**Comment by vogdb** [comment]
Done in #2542
