### ISSUE TITLE
Introduce CM_Api_Exception

### ISSUE THREAD

**Issue by fauvel** [cargomedia/cm#2293]
These exceptions should contain a list of errors (usually validation errors) in both a machine- and a human-readable format: Error message (translated), resource name (optional), field name (optional) and error code, similar e.g. to the [GitHub API](https://developer.github.com/v3/#client-errors).

**Comment by njam** [comment]
As discussed let's do it like github:
```
{
  "message": "ValidationFailed",
  "errors": [
    {
      "resource": "Issue",
      "field": "title",
      "code": "missing_field"
    }
  ]
}
```

- message: mandatory, 1 word error name
- errors: optional, array of hashes with additional error information
 - code: mandatory
 - field: optional

**Comment by fauvel** [comment]
Closing as discussed
