### ISSUE TITLE
Ensure mongodb client will fallback to different server/router

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2320]
We pass a list of MongoDB routers to the mongodb client:

``` php
    $config->services['MongoDb'] = [
        'class'     => 'CM_MongoDb_Client',
        'arguments' => [
            'config' => [
                'db'      => 'example',
                'server'  => 'mongodb://localhost:27017,www3.example.com:27017,www4.example.com:27017,search2.example.com:27017',
                'options' => ['connect' => true, 'username' => 'example', 'password' => 'example', 'db' => 'example'],
            ],
        ],
    ];
```

Just today we experienced that one of these routers was down, and as a result many web processes' mongodb queries timed out after 60 seconds.

Let's investigate how the PHP client behaves if 1 router is down.
How can we minimize the impact, so that the client will fall back to a different router as soon as possible.

@alexispeter @fvovan @zazabe maybe for you?

**Comment by fvovan** [comment]
I didn't try to reproduce anything but just read the docs yet.
 First of all I see that `replicaSet` option is not used, and according documentation it means 

> Automatic failover will not work correctly if replicaSet is not specified.

So it looks like it just checks server status for the moment of initial connection and doesn't care about reconnections after its crashing.

But even if this param is set and  primary node is down then some delay on write operations will occur.

>During this time (» 20-60 seconds), the connection will not be able to perform any write operations and attempts to do so will result in an exception. Connections to secondaries will still be able to perform reads.

The  way to decrease this interval is (as usual :) ) to upgrade mongoDb to 3.2.  It introduces specific settings for election.

> For instance, it may take 10-30 seconds for the members of a replica set to declare a primary inaccessible (see electionTimeoutMillis). One of the remaining secondaries holds an election to elect itself as a new primary. The election itself may take another 10-30 seconds.
Changed in version 3.2: Starting in MongoDB 3.2, with the replication election enhancements, MongoDB reduces replica set failover time. See replication election enhancements for details.

And the last note is `MongoClient` is deprecated now. It might be we would like to replace it later?

@njam wdyt?

**Comment by njam** [comment]
I see.
Can we upgrade to the new mongodb PHP driver http://php.net/manual/en/set.mongodb.php while we're still on Mongodb 2.6? If yes, then let's do it, to not spend time on an outdated version.

**Comment by alexispeter** [comment]
We can.
 https://docs.mongodb.com/ecosystem/drivers/php/#drivers
