### ISSUE TITLE
Improve JS error reporting

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2328]
Expand `jserror.js` to allow to report errors programmatically. Changes:
- Send data with an `XMLHttpRequest` (POST)
- Keep last N log entries in `cm.log`, and send them to the server in `jserror.log()`
- Add "metaInfo" to `CM_Exception`
 - Expect it in `jserror.js` and send it to the server

cc @zazabe @vogdb

**Comment by zazabe** [comment]
close, done in https://github.com/cargomedia/cm/pull/2334
