### ISSUE TITLE
Make sure IDs are strings/enums in Loggly

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2329]
Currently IDs (user-id, showSession-id, viewSession-id) are showing up as *numbers* in Loggly, which makes it impossible to aggregate on them. It works fine for strings.

Suggestion:
- Always log PHP objects as Hashes. E.g. `user: {id: 123, username: "foo"}`
- In Loggly handler add special case for "id", and make it a string

Tested: it works fine if we send the (numerical) ID as a string to Loggly!

**Comment by fvovan** [comment]
Maybe it would be better to convert all numeric values to strings then?

**Comment by njam** [comment]
No, we actually have some numerical values like "FPS", which we want to average, sum up etc.

**Comment by zazabe** [comment]
btw, i think it's a bit related to https://github.com/cargomedia/cm/pull/2330#issuecomment-248312432

**Comment by njam** [comment]
@tomaszdurka could you look into this?

**Comment by zazabe** [comment]
done by #2379
