### ISSUE TITLE
Improve JS stacktrace in prod with  stacktracejs/stacktrace-gps

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm#2336]
https://github.com/stacktracejs/stacktrace-gps/ can be use to parse an Error stacktrace and map it with a sourcemaps.

With `cm-bundler`, minified js bundles in prod will not have a sourcemaps in most cases, but we can re-generate the sourcemaps on the server side to improve the error stacktrace before logging it.

wdyt @njam @vogdb ?

_waiting for https://github.com/cargomedia/cm/pull/2274_

**Comment by vogdb** [comment]
good idea

**Comment by njam** [comment]
Not needed for now
