### ISSUE TITLE
Implement static-test-time for microtime function

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#2353]

**Comment by njam** [comment]
With runkit?
Note that runkit is not available for PHP 7.
We've been discussing to replace it in https://github.com/cargomedia/cm/pull/2000

**Comment by tomaszdurka** [comment]
Well I am aware, but we still use it currently for time. I wanted to make microtime aligned with time. Currently time is static, other one moves :) Once we remove runkit we make them both dynamic again I guess.

**Comment by tomaszdurka** [comment]
So I understand you would rather invest time in solving #2000.
Makes sense.

Closing in favor of #2000. For tests failing we will compare strictly with microtime where needed.
