### ISSUE TITLE
Floatbox.disable

### ISSUE THREAD

**Issue by vogdb** [cargomedia/cm#2402]
It would be great to have a method to disable/enable floatbox's content to any user input. Use case is when we doing some pending action and it is not desired to change anything on the page. For example, rotating pictures.

@njam @christopheschwyzer any notes?

**Comment by njam** [comment]
I would try to avoid it if we can.
Why do we need to disable the UI in this case? Wouldn't it be enough to disable the "rotate" button? If a user clicks another button while the photo is being rotated it doesn't hurt much, does it?

**Comment by vogdb** [comment]
Well, I wanted to disable navigating too. Do you think that is too much?

**Comment by njam** [comment]
It's not so nice for the user to disable UI, and if it's not 100% necessary I would not do it.
If I rotate an image, and it takes longer than expected then I think it's good if I can navigate away.

**Comment by vogdb** [comment]
ok!
