### ISSUE TITLE
ForkHandler cannot send data to parent through IPC

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2433]
The error about broken pipes definitely happens more often recently. I think it happens when a child process exits, so it's obvious that it happens more often since child processes exit regularly (https://github.com/cargomedia/cm/pull/2414).

```
E_NOTICE: fwrite(): send of 128 bytes failed with errno=32 Broken pipe
#0 /home/example/releases/20161124123216/vendor/cargomedia/cm/library/CM/Process/ForkHandler.php(83): {throw}
#1 (): [internal function]
#2 /home/example/releases/20161124123216/vendor/cargomedia/cm/library/CM/Process/ForkHandler.php(83): fwrite(resource, 'O:25:"CM_Process_WorkloadResul...')
#3 /home/example/releases/20161124123216/vendor/cargomedia/cm/library/CM/Process.php(221): CM_Process_ForkHandler->runAndSendWorkload()
#4 /home/example/releases/20161124123216/vendor/cargomedia/cm/library/CM/Process.php(279): CM_Process->_fork(Closure, 28)
#5 /home/example/releases/20161124123216/vendor/cargomedia/cm/library/CM/Process.php(158): CM_Process->_wait(true, false)
#6 /home/example/releases/20161124123216/vendor/cargomedia/cm/library/CM/Cli/CommandManager.php(178): CM_Process->waitForChildren(true)
#7 /home/example/releases/20161124123216/bin/cm(18): CM_Cli_CommandManager->run(CM_Cli_Arguments)
#8 ./bin/cm(0): {main}
```
https://cargomedia.loggly.com/search#terms=%22send%20of%20128%20bytes%20failed%22

Probably the parent is already gone. Needs investigation.

**Comment by njam** [comment]
@alexispeter wanna investigate?

**Comment by alexispeter** [comment]
sure

**Comment by alexispeter** [comment]
Killing off the parent will cause this error to pop up as soon as the worker reaches it's limit and tries to send the result back to the parent.

The next question is, why does the parent die so often?

**Comment by njam** [comment]
So it's happening when the parent process dies unexpectedly (and thus cannot signal the children to exit)? I'm wondering what systemd does in that case. I hope it kills all processes in the *control group* (including all children) before it starts the service again. Could you check it?

If all this works fine, then I think we might just ignore this error. Maybe we can check if the IPC stream is still open/writable before writing to it?

**Comment by alexispeter** [comment]
Systemd seems to be unwilling to kill children. Instead it abandons them and creates a new parent.

**Comment by njam** [comment]
We discussed to close it in favor of https://github.com/cargomedia/cm/issues/2435

**Comment by njam** [comment]
Foreman systemd configuration issue: https://github.com/cargomedia/puppet-cargomedia/issues/1646
