### ISSUE TITLE
Email validation mismatch

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2439]
Email address: `foo@example..com`

This email is valid according to our form field, but then triggers and error in the Swift mailer:
> Swift_RfcComplianceException: Address in mailbox given [foo@example..com] does not comply with RFC 2822, 3.6.2. in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 347

Probably we should make the form field validation stricter?

**Comment by fvovan** [comment]
Hmm. could it be that mentioned value was not validated at all (or it was validated few years ago with older PHP version, I remember `FILTER_VALIDATE_EMAIL` was improved with 5.4 or 5.5) ?

It does not passes validation on the example component and in general  `filter_var('foo@example..com', FILTER_VALIDATE_EMAIL)` returns `false`.

![screen shot 2016-12-09 at 15 00 46](https://cloud.githubusercontent.com/assets/2360687/21051542/1420eb40-be21-11e6-9ebb-4064c3d15e25.png)

How it can be reproduced?

**Comment by fauvel** [comment]
Agree, I think we can close this.
