### ISSUE TITLE
Services dependencies (plugin architecture)

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#2448]
I wanted to make one service subscribe to the other one. So whenever other is instantiated the first one is also instantiated. Main reason for that was to register clockwork maintenance jobs from different services instead of clustering them all in Maintenance_Cli.

I've described the idea to @njam and he suggested that maybe whole concept is related to something broader (like module/plugin) rather than to a services. 

Let's investigate how others do it. From my first perspective services were kind-of nice flexible, top-level components. I would prefer to not put anything on top of it as it will bring conventions and extra interfaces.

**Comment by njam** [comment]
Let's say the module *Maxmind* wants to register a cron job with *Clockwork*.

Either we define it with code:
```php
CM_Maxmind_Service {

  public function onServiceRegistration($serviceManager) {
    $clockwork = $serviceManager->get('clockwork');
    $clockwork->register('8 days', $this->_upgradeMaxmindDatabase);
  }

}
```

Or with a config file `CM/Maxmind/module.json`:
```json
{
  "clockwork-jobs": {
    "CM_Maxmind_Service::upgradeMaxmindDatabase": "8 days"
  }
}
```

**Comment by tomaszdurka** [comment]
Simple implementation based on services can be found:
https://github.com/cargomedia/cm/compare/master...tomaszdurka:services-dependency

I like the Definition class added here regardless of the dependency solution.
