### ISSUE TITLE
Remove ability to have multiple actions per form

### ISSUE THREAD

**Issue by christopheschwyzer** [cargomedia/cm#2450]
Instead have a single action. This will make a few things easier. Let's check if and how we use multiple actions currently.

Alternatively: move required fields to form (to allow edit+create actions)

**Comment by njam** [comment]
We use 2 actions for many forms (usually "Create" and "Save").
Let's keep this, and rather just move required fields from the action to the form.
See https://github.com/cargomedia/cm/pull/2455
