### ISSUE TITLE
Redesign form fields

### ISSUE THREAD

**Issue by christopheschwyzer** [cargomedia/cm#2465]
- Placeholder & label
- Error message
- Auto save
- Highlight *required* fields (`$form->isRequiredField($name)`)
- Rethink checkboxes (in case of large amount of options - >10?!)
- …

Examples:
- [Material Design](https://material.google.com/components/text-fields.html#text-fields-required-fields)

**Comment by christopheschwyzer** [comment]
<img width="455" alt="screen shot 2016-12-13 at 10 58 22" src="https://cloud.githubusercontent.com/assets/1888817/21135726/1e856c8c-c123-11e6-84cb-ffef99bad548.png">

**Comment by christopheschwyzer** [comment]
I think we could simplify the markup a bit. E.g. I think it would make sense to put the label inside the respecting form field. I'm not even sure we need this wrapper `<div class="formField …">` @njam wdyt?

**Comment by njam** [comment]
We currently have 2 separate smarty functions:
- `smarty_function_input`: returns only the html from the `CM_FormField_Abstract`'s template
- `smarty_function_formField`: Wraps the field's html into `<div class=formField></div>` and adds `<label>` and `<div class="input">`.

There are probably a few places where we use `smarty_function_input` when we don't want a label. We will need to check those occurences. Not sure if they should or should not use form fields.

**Comment by christopheschwyzer** [comment]
Yes. I think it should be possible to combine them into one. For accessibility reasons we should always have a label anyways. And then just hide it with some flag if desired - let me think about it.

**Comment by christopheschwyzer** [comment]
Related. For better selection UI https://github.com/Fabianlindfors/multi.js
