### ISSUE TITLE
Cannot json_encode value of request URL

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2482]
JSON encoding of the request's URL fails in the GoogleAnalytics client, when we try to encode the request's URI:
```php
$js .= 'ga("send", "pageview", ' . CM_Params::jsonEncode($pageView) . ');';
```

The error code from `json_last_error` is 5 (`JSON_ERROR_UTF8`).
The string that's being encoded (request URI) looks like this:
- [Loggly](https://cargomedia.loggly.com/search#terms=%22Cannot%20json_encode%20value.%22): `/users/friends1008(13) ?? - ...`
- [New Relic](https://rpm.newrelic.com/accounts/350429/applications/2137721/filterable_errors#/table?top_facet=transactionUiName&primary_facet=error.message&barchart=barchart&filters=%5B%7B%22key%22%3A%22error.class%22%2C%22value%22%3A%22CM_Exception_Invalid%22%2C%22like%22%3Afalse%7D%2C%7B%22key%22%3A%22error.message%22%2C%22value%22%3A%22Noticed%20exception%20%27CM_Exception_Invalid%27%20with%20message%20%27Cannot%20json_encode%20value.%27%20in%20%2Fhome%2Ffuckbook%2Freleases%2F20170104144933%2Fvendor%2Fcargomedia%2Fcm%2Flibrary%2FCM%2FUtil.php%3A559%22%2C%22like%22%3Afalse%7D%5D&_k=9obyk3): `/users/friends1008(13) 信息 - ...`

Probably the truth lies inbetween.

We *are* sanitizing the request URL in `CM_Http_Request_Abstract::__construct()` using `CM_Util::sanitizeUtf()`:
```php
mb_convert_encoding($value, 'UTF-8', 'UTF-8');
```
This seems this doesn't cover all cases.

Unfortunately I am not able to reproduce so far with the example strings from above.

---

Example stack trace:
```
#0 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Util.php(559): {throw}
#1 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Params.php(669): CM_Util->jsonEncode('/users/friends1008(13) ??_? ...', NULL)
#2 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CMService/GoogleAnalytics/Client.php(130): CM_Params->jsonEncode('/users/friends1008(13) ??_? ...')
#3 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CMService/GoogleAnalytics/Client.php(203): CMService_GoogleAnalytics_Client->getJs()
#4 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Service/Trackings.php(18): CMService_GoogleAnalytics_Client->getHtml(CM_Frontend_Environment)
#5 /home/example/releases/20170104144933/tmp/smarty/SK_View_Document_100_zh^ab3d34363883aaf5c6013b0d9d8bc900469d0f67.file.default.tpl.php(143): CM_Service_Trackings->getHtml(CM_Frontend_Environment)
#6 /home/example/releases/20170104144933/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(182): content_586d0c26733a63_87794012(Smarty_Internal_Template)
#7 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Frontend/Render.php(85): Smarty_Internal_TemplateBase->fetch()
#8 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Frontend/Render.php(491): CM_Frontend_Render->fetchTemplate('library/SK/layout/default/View...', [], [])
#9 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Frontend/Render.php(499): CM_Frontend_Render->fetchViewTemplate(SK_View_Document, 'default', [])
#10 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/RenderAdapter/Document.php(66): CM_Frontend_Render->fetchViewResponse(CM_Frontend_ViewResponse)
#11 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Page.php(58): CM_RenderAdapter_Document->fetch()
#12 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Page.php(143): CM_Http_Response_Page->_renderPage(CM_Page_Error_NotFound)
#13 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Abstract.php(280): CM_Http_Response_Page->{closure}()
#14 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Page.php(152): CM_Http_Response_Abstract->_runWithCatching(Closure, Closure)
#15 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Page.php(95): CM_Http_Response_Page->_processPage(CM_Http_Request_Get, CM_Http_Response_Page_ProcessingResult)
#16 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Page.php(82): CM_Http_Response_Page->_processPageLoop(CM_Http_Request_Get)
#17 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Page.php(64): CM_Http_Response_Page->_processContentOrRedirect()
#18 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Response/Abstract.php(48): CM_Http_Response_Page->_process()
#19 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Http/Handler.php(28): CM_Http_Response_Abstract->process()
#20 /home/example/releases/20170104144933/public/index.php(9): CM_Http_Handler->processRequest(CM_Http_Request_Get)
#21 /home/example/releases/20170104144933/vendor/cargomedia/cm/library/CM/Bootloader.php(163): {closure}()
#22 /home/example/releases/20170104144933/public/index.php(11): CM_Bootloader->execute(Closure)
#23 /home/example/serve/public/index.php(0): {main}
```

**Comment by njam** [comment]
@fvovan @fauvel any ideas?

**Comment by fauvel** [comment]
Since it looks like malformed UTF-8, let's interpret these strings as ASCII in `CM_Util::sanitizeUtf` if json_encode is throwing a `JSON_ERROR_UTF8`! Wdyt?

**Comment by fauvel** [comment]
For unit testing, you can use malformed UTF-8 strings like `"\xB1\x31"` (actually ISO-8859-1), which should be sanitized as `"±1"`.

**Comment by njam** [comment]
There are many things we can try to sanitize UTF8 it seems. It's very difficult to judge if something is going to succeed or not from that perspective (and if it's going to have side effects).
- `iconv("UTF-8","UTF-8//IGNORE",$string);`: converts from utf8 to utf8, ignoring invalid chars
- `iconv("UTF-8","UTF-8//TRANSLIT",$string);`: converts from utf8 to utf8, transliterating invalid chars
- `mb_convert_encoding($value, 'UTF-8', 'UTF-8')`: converts from utf8 to utf8
- `utf8_encode($string)`: converts from ascii to utf8

Compare with http://stackoverflow.com/questions/3715264/how-to-handle-user-input-of-invalid-utf-8-characters

The example you posted ("\xB1\x31") is not causing any error when filtered by the current `sanitizeUtf()`.

How about we catch the condition like you suggest in `santizeUtf()`, but then log a warning with a hex-notation of the string, so we can try to reproduce and examine it?

**Comment by fauvel** [comment]
- `utf8_encode` actually converts from ISO-8859-1 to UTF-8. Since ISO-8859-1 has long been a web standard, the root case might be that some web browsers are still sending headers encoded as ISO-8859-1, so `utf8_encode` would be exactly what we need. And this function never throws.
- `iconv("UTF-8", "UTF-8//TRANSLIT", $string)` will throw by itself if `$string` is malformed UTF-8 (transliteration only works for converting a valid source string to a different charset which is not a superset of the source charset)
- `iconv("UTF-8", "UTF-8//IGNORE", $string)` might be an option, but maybe it is identical to `mb_convert_encoding($value, 'UTF-8', 'UTF-8')`. Our use case in `json_encode`, so we should check exactly this imo.
- Logging is definitely a good idea! We could log the strings interpreted as ASCII, using hex notation for non-printable characters.

**Comment by njam** [comment]
Let's add the logging so we can be sure to fix it properly.
Wanna implement it in a separate PR?

**Comment by fauvel** [comment]
Just to be clear - do you want to keep `CM_Util::sanitizeUtf` functionally as is, and only add logging if `json_encode` fails? Or do you also want to use `utf8_encode` to sanitize strings in this case?

**Comment by fvovan** [comment]
Just noticed the conversation.
don't we already have the logging in `CM_Log_Handler_MongoDb::_sanitizeRecord()` ?

**Comment by fauvel** [comment]
How do the MongoDB records look like?

**Comment by njam** [comment]
We have the logging for MongoDB, but here it fails in the GoogleAnalytics code.

My idea was to detect that json encoding *would* fail in `sanitizeUtf()`, and then log an extra entry.
This would be temporary, to catch the string that's causing this.

**Comment by fvovan** [comment]
ahhh. okay.
btw. there is an error in mongodb handler as well, `_sanitizeRecord` is called twice

**Comment by njam** [comment]
Ah we have it MongoDB from the GA error, but it's not visible to fluentd (why?).

```
CM_Exception_Invalid: Cannot json_encode value. in /home/example/releases/20170105093126/vendor/cargomedia/cm/library/CM/Util.php on line 559
[...]

Exception meta info:
Array
(
    [value] => '/users/friends1019(15) 信?_? - Example'
    [jsonError] => 'json error code: `5`'
)
[...]

Logger notifications
Array
(
    [sanitizedFields] => Array
        (
            [code] => 434d5f5574696c2d3e6a736f6e456e636f646528272f75736572732f667269656e6473313031392831352920e4bfa1e65faf202e2e2e272c204e554c4c29
            [value] => 272f75736572732f667269656e6473313031392831352920e4bfa1e65faf202d204675636b626f6f6b27
        )

)
```

**Comment by njam** [comment]
Possible fix (https://github.com/cargomedia/cm/pull/2485) released: 2017-01-06

**Comment by njam** [comment]
There's a new case :(
```
    [sanitizedFields] => Array
        (
            [code] => 434d5f5574696c2d3e6a736f6e456e636f646528272f702f4e30656d69313030394e30656d6920e75f5fe4b8aae4babae8b55f2e2e2e272c204e554c4c29
            [value] => 272f702f4e30656d69313030394e30656d6920e75f5fe4b8aae4babae8b55fe65f5f202d204675636b626f6f6b27
        )
```

Sanitizing the string *again* makes it work.
I would suggest that we detect this case and log it, *before* sanitizing it.
wdyt?
Could you add the debug code?

**Comment by fvovan** [comment]
i'll do it

**Comment by njam** [comment]
Logging released 2017-01-09:
https://cargomedia.loggly.com/search#terms=%22Non%20utf-8%20uri%22

No events yet. Strange.

**Comment by njam** [comment]
New case:
- 2 "cannot json_encode value": https://cargomedia.loggly.com/search#terms=%22Cannot%20json_encode%20value%22
- 0 "non utf-8 uri": https://cargomedia.loggly.com/search#terms=%22Non%20utf-8%20uri%22

**Comment by fvovan** [comment]
I suspect it might be `parse_url()` error. There are some reports that it's not _fully_ utf-8 capable.
so at the point of `CM_Http_Request_Abstract::setUri()` call its argument is fine. 
how about we move logging to `setUri()` ?  (and add temp `$originalUri` param to log unsanitized value as well )?
@njam  wdyt?

**Comment by njam** [comment]
sgtm
Maybe to keep it simpler do all of it in the constructor? Call `setUri()` and then check if the value of `getUri()` can be json encoded?

**Comment by njam** [comment]
@zazabe  is working on introducing the library League/Uri for parsing and processing URLs in CM (https://github.com/cargomedia/cm/issues/2486). They have their own sanitization routines.
Let's put this on hold, as it might be solved by using League/Uri.

**Comment by njam** [comment]
@fvovan could you check if there are any recent errors, and what the cause is?

**Comment by fvovan** [comment]
last 3 happened on 11/02 
the reason is the same - URL
And nothing was logged with "Non utf-8 uri".

**Comment by njam** [comment]
let's adjust the logging as planned then: https://github.com/cargomedia/cm/pull/2507

**Comment by fvovan** [comment]
Okay, and just for the info, was League/Uri released (or at least merged)?

**Comment by zazabe** [comment]
League/Uri > reverted, for perf reason... :(

**Comment by njam** [comment]
new logging (https://github.com/cargomedia/cm/pull/2507) added: 2017-02-17

**Comment by njam** [comment]
@fvovan there's a new case in Loggly. Could you investigate?

**Comment by fvovan** [comment]
really weird
so we have 3 values 
```
path:         2f7a682f702f73e25fa6
originalUri:  2f7a682f702f73e280a6
sanitizedUri: 2f7a682f702f73e280a6
```
the last two are equal, that means sanitizing doesn't change anything.
But I don't know how the first one has appeared. the difference is only 1 byte (`2f7a682f702f73e2_5f_a6`) and it's hard to say where it's changed. Nothing special happens between `setUri()` and `getPath()`.
I tried 
```
$req = new CM_Http_Request_Get(pack('H*', '2f7a682f702f73e280a6'));
echo unpack('H*', $req->getPath())[1];
```
and it returns unmodified value without any errors. Also i tried to extract selected strings from `setUri()` and run them 1 by 1. The result is the same.
 I would not say that it's RAM fluctuations but other thoughts look no much reasonable.
And may be let's try to test encoding possibility and logging of `$path` right after `parse_url()` ?
@njam wdyt?

**Comment by njam** [comment]
- We can reproduce it on production, but not on development.
- We can reproduce it in php-fpm, but not on CLI, with this script:
```php
#!/usr/bin/env php
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';
$bootloader = new CM_Bootloader(dirname(__DIR__) . '/');
$bootloader->load();

$req = new CM_Http_Request_Get(pack('H*', '2f7a682f702f73e280a6'));
echo unpack('H*', $req->getPath())[1];
``` 
Executed in fpm with:
```
REQUEST_METHOD=GET SCRIPT_NAME=test.php SCRIPT_FILENAME=/home/example/serve/scripts/test.php QUERY_STRING='' cgi-fcgi -bind -connect 127.0.0.1:9000
```
---

After some debugging we found that a kernel upgrade fixed the problem:
- old: Linux app2 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64
- new: Linux app2 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64

We will upgrade all machines and keep an eye on the logs.

**Comment by njam** [comment]
All app servers rebooted with new kernel: 2017-02-21

**Comment by njam** [comment]
No new incidents! Hurray!
