### ISSUE TITLE
Class for representing a link target (URL)

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2486]
There are differently "complete" representations of a URL:
- A: **Absolute URL**. Can be used directly.
- B: **Relative URL**: e.g. `/example`. Only in combination with a *Render* it can become a full URL. It can be passed to the client, and the client can convert it to a full URL.
- C: **Page Classname**: e.g. `CM_Page_Example`. Only in combination with a *Render* it can become a full URL.

Each of these representations can optionally include *parameters*.

Usages of such URL representations include:
- smarty_function_linkUrl(): param `page` is a *page classname*, param `params` is URL params
- CM_Page_Abstract::getPath(): returns a *relative URL*
- CM_MenuEntry: option `page` Is a *page classname*, option `params` is URL params
- CM_Http_Response_Page::redirect: *page classname* and URL params
- CM_Http_Response_Page::redirectUrl: *absolute URL*

I think it would make sense to wrap the representation of such URLs into an object, so we **can pass it along as one variable**.

I'm not sure all the different use cases should be wrapped into a single class. Case A) and B) are generic use cases (and already covered to some extent in `CM_Http_UrlParser`), while C) is specific to our framework. Nevertheless it would be nice if there was one type that could be passed along that represents either of the three options.

@dlondero @tomaszdurka @zazabe wdyt?

**Comment by zazabe** [comment]
For A and B, we could use something like http://uri.thephpleague.com/4.0/uri/schemes/http i guess, it's [PSR-7 compliant](http://www.php-fig.org/psr/psr-7/#psrhttpmessageuriinterface), and it seems to support relative paths (host/scheme/... don't need to be specified).
Then, we can [probably extend the URI object](http://uri.thephpleague.com/4.0/uri/extension/) to support case C

**Comment by zazabe** [comment]
Draft version with [league/uri](https://packagist.org/packages/league/uri) : https://github.com/cargomedia/cm/pull/2491

**Comment by zazabe** [comment]
as discussed with @njam:

- introduce a new `CM\Url` namespace
- introduce interfaces: `FullUrlInterface`, `RelativeUrlInterface` and `PageUrlInterface`    
- implement those interfaces via classes inheriting from vendor URI object

**Comment by tomaszdurka** [comment]
I have my doubts about these implementing this interface. As looked thought URI interface it seems it should implement method `getHost()` which returns string host. I understand that Page itself will not be able to do it? We do not know he host from Page level, we can only create insufficient object with no host set and add it (if there's a way) later. Same goes for scheme.

**Comment by zazabe** [comment]
Yes, but we can restrict `RelativeUrl` and make it invalid if a host/scheme is set, see https://github.com/thephpleague/uri/blob/4.x/src/Schemes/Generic/AbstractUri.php#L328, could be enough, isn't it?
