### ISSUE TITLE
Convert Jobdistribution into service

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2490]
Instead of queueing a job to gearman from within `CM_Jobdistribution_Job_Abstract` we would like to introduce a general job-distribution service, which has functions to queue a job from the outside.

Some code is available here: https://github.com/cargomedia/cm/pull/1659

**Comment by alexispeter** [comment]
What were the reasons for the original code to be discontinued? At a quick glance, it looks rather finished with only tests and ci causing some problems.

cc @tomaszdurka

**Comment by tomaszdurka** [comment]
Reimplemented in #2513
