### ISSUE TITLE
Remove default site and CM_Site_Abstract::factory method

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#2504]
Let's try to remove all the `CM_Site_Abstract::factory()` usages and method itself from the codebase. This will also get rid of default site concept.

**Usages without argument**
This way of invoking the method returns the default site. This is used extensively in tests. In those cases let's replace it with call to newly created `CMTest_TH::getDefaultSite`, a method which returns singleton instance of mocked site.
Unfortunately we also use default site in the real code:
- `CM_Http_Request_Abstract::popPathSite`
- `CM_Http_Request_Abstract::popPathSiteByMatch`
The goal is to remove this functionality, but first let's check if there are requests without site (let's log warning if so).

**Usages with argument**
This way of invoking the method searches for site by certain type. 
There are only several usages in the codebase. Let's replace it with `CM_Site_SiteFactory::findById`. This new method would search through the instance's siteList by type and return it (let's keep the name `findById` already).

**Comment by fvovan** [comment]
there are some other places
```
CM_Frontend_Environment::getSite()
CM_Mail_Mailable::__construct()
CM_Model_User::getSite()
```
it seems not hard to make `$site` param mandatory for `CM_Frontend_Environment`. i created test helpers for it.
probably we can make `$site` non-optional for `CM_Model_User` as well
but not sure how to proceed with `CM_Mail_Mailable`

**Comment by njam** [comment]
It will not be possible to remove the usage of a *default site* from `CM_Model_User::getEnvironment()` (changed recently!). The whole purpose of this code is to have a fallback to the *default site* if the user doesn't have one configured.
So we need to keep a `Site::getDefaultSite()` I think.

**Comment by tomaszdurka** [comment]
Ok, if we keep default site, I would change the way we store it. With new approach supporting multiple site with the same (type/className) we cannot use classname as default indicator. We need unique id which is stored in database. I would then keep it in application persistence (no config). Either as unique param for site row in database or entry in additional table (maybe CM_Option?).

**Comment by fvovan** [comment]
okay, so let's include it in https://github.com/cargomedia/cm/issues/2505 ?

**Comment by njam** [comment]
Agree, we should store a *default site ID* in the database. CM_Option sound ok for this.
We could also make it optional to set a default, and in that case use the first available site.

**Comment by tomaszdurka** [comment]
I agree to introduce default site-id in #2505, but I would still make some changes in this one.

Let's replace factory usages as written in description:
- with argument `CM_Site_SiteFactory->findById()`
- without argument `CM_Site_SiteFactory->getDefault()`

**Comment by fvovan** [comment]
sgtm
