### ISSUE TITLE
Introduce job-server adapter pattern for Jobdistribution

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2511]
Introduce job-server adapter for CM_Jobdistribution, currently just for Gearman.
In the future we should be able to use other adapters, like [RabbitMQ](http://www.rabbitmq.com/tutorials/tutorial-two-php.html).

Wait for https://github.com/cargomedia/cm/issues/2490

**Comment by tomaszdurka** [comment]
Introduced in #2513.
