### ISSUE TITLE
Migration: scripts should have access to service manager

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2515]
Part of https://github.com/cargomedia/cm/issues/2403

Either we pass it to `up()`  or make the scripts `CM_Service_ManagerAware` (probably better).
@zazabe @tomaszdurka wdyt?

**Comment by zazabe** [comment]
it's already done i think: https://github.com/cargomedia/cm/blob/master/library/CM/Migration/Loader.php#L74

**Comment by njam** [comment]
True.
But would be good to make the default template implement that interface, wdyt?
Probably would be enough to implement the interface and `use CM_Service_ManagerAwareTrait;`.

**Comment by zazabe** [comment]
by "default template" you meant the generated migration scripts? 
like this: https://github.com/cargomedia/cm/pull/2517 ?

**Comment by njam** [comment]
yes!
