### ISSUE TITLE
Don't fork php process

### ISSUE THREAD

**Issue by alexispeter** [cargomedia/cm#2524]
To avoid problems with resource sharing (e.g. MongoDB socket https://github.com/cargomedia/sk/issues/4424).

There are two usages:
- CLI Manager. Can be replaced by letting systemd run multiple processes. https://github.com/cargomedia/puppet-cargomedia/issues/1772
- Clockwork Manager. Could be replaced by running events in job-distribution. https://github.com/cargomedia/cm/issues/2525

**Comment by fauvel** [comment]
As a best practice, we should also close these resources just before forking (especially MySQL and MongoDB connections), otherwise the fastest process would close them unexpectedly for the other ones when it finishes.

**Comment by njam** [comment]
We call `CM_Service_Manager::getInstance()->resetServiceInstances();` in `_fork()` to make sure all connections to databases etc are re-established. But in the future we could even remove `_fork()`.
