### ISSUE TITLE
Return boolean "changed" from Model::_set()

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2531]
Make `Model::_set()` return a boolean value that indicates if at least one field was changed.

Discussed with @alexispeter 
@tomaszdurka wdyt?

**Comment by njam** [comment]
@tomaszdurka wdyt?

**Comment by tomaszdurka** [comment]
Oh I think we discussed that once briefly. I think it is fine to return here, but probably having some kind of event manager which emits events (with additional) data could bring much more value. 
Simple solution would be to use eventmanager trait we have on the model. We would need to create those bindings in the constructor of the class though. Which is fine I guess.
Advantage over simple return is that we can trigger events with a bit more complex values (objects) including 'real change' flag or value it has updated to. Probably in exchange for little performance.

We could additionally (or later) introduce eventmanager singleton to monitor those events within application, so other services could listen on it. 
*Currently our application relies on global service manager which is requested in actions like _set, to get persistence layer and write to it. We could request eventmanager in the same fassion and trigger those change events there.*

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/sk/issues/4489
