### ISSUE TITLE
Adjust profile online/offline status

### ISSUE THREAD

**Issue by christopheschwyzer** [cargomedia/cm#2533]
Change `smarty_function_user_activity`:

Show nothing after 14 days (instead of 10 days now)
Don't display time period when user was online, instead just: "Recently online"

**Comment by christopheschwyzer** [comment]
Closing in favor of PR: https://github.com/cargomedia/cm/pull/2534

**Comment by njam** [comment]
You can type "Closes #2533" anywhere in the pull request. Then when you merge the pull request the ticket will automatically be closed.

**Comment by christopheschwyzer** [comment]
Ah yes 👍
