### ISSUE TITLE
Introduce primary key on cm_action

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2536]
We need a primary key on the table, so that we can use "pt-online-schema-change" (see https://github.com/cargomedia/puppet-cargomedia/issues/1781).

I think we need to introduce a new column, like "id".
Can we use "pt-online-schema-change" to introduce a primary column?

@alexispeter wdyt? Could you do the change?
cc @fvovan @kris-lab

**Comment by fvovan** [comment]
done
