### ISSUE TITLE
Enable "cm.debug.viewTree()" on production

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2552]
The idea was for product development to have a tool to quickly see the view-structure of a page.
Unfortunately `cm.logger.info()` is not visible on production.

@zazabe what's the best way here?
Could be only for users with the *developer* role.

**Comment by zazabe** [comment]
one way, already available:

<img width="663" alt="screen shot 2017-02-02 at 18 50 08" src="https://cloud.githubusercontent.com/assets/401598/22561432/79425afe-e978-11e6-891f-39213a3557bc.png">

**Comment by njam** [comment]
I was hoping to have the DevTools-reference to the "HTMLDivElement". This way when you hover over it the element is highlighted in the viewport.

**Comment by zazabe** [comment]
It's more a hack, but we can easily change the `viewTree()` implementation and not use the logger at all. 
We could even use `console.group()`, like this:

<img width="1095" alt="screen shot 2017-02-03 at 10 54 46" src="https://cloud.githubusercontent.com/assets/401598/22586839/44e67506-e9ff-11e6-92fb-513680bfa2ff.png">

**Comment by zazabe** [comment]
see https://github.com/cargomedia/cm/pull/2556/files

**Comment by njam** [comment]
Done in https://github.com/cargomedia/cm/pull/2556

@NicolasSchmutz let's discuss
