### ISSUE TITLE
Rethink how we generate Urls

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm#2564]
Maybe remove League\Url and use GuzzleHttp instead because of performance issues

related to #2535, https://github.com/cargomedia/cm/pull/2563 (revert) and https://github.com/cargomedia/cm/pull/2562

**Comment by zazabe** [comment]
Guzzle\Psr7\Uri  seems not an option, mostly everything is `private`, would be hard to extend it...
see https://github.com/guzzle/psr7/issues/37 and https://github.com/guzzle/psr7/pull/72#issue-141914805

**Comment by njam** [comment]
I see, so we copy it?
