### ISSUE TITLE
Remove forking from CLI manager

### ISSUE THREAD

**Issue by njam** [cargomedia/cm#2585]
Part of https://github.com/cargomedia/cm/issues/2524

Please make sure that the CLI exits with non-0 code on failure, to fix https://github.com/cargomedia/cm/issues/2583

**Comment by alexispeter** [comment]
@njam What will happen to the keep-alive functionality? I assume this is default behaviour for foreman-daemons, but keepalive also makes it so cli-commands aren't tracked in newrelic. Should we keep using annotations for this? Or maybe introduce a special parameter we only use for daemons?

**Comment by njam** [comment]
Keep-alive is handled by systemd. It can be removed completely.

Let's remove New Relic tracking for CLI commands.
