### ISSUE TITLE
CM website

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm#950]
What do you guys think about CM framework website. I think we miss a lot of user docu on stuff like events, childrenEvents, actions, etc.

I discussed problem with @christopheschwyzer and we thought it would be the best to make it in CM itself. This way we could have live examples, code snippets.

Problem is that CM is not so easily deployable yet. That's why I would suggest to rather create first documentation based on jekkyl and github.io. We can easily add text and once CM is easy to push we can move it there.

@cargomedia/dev Suggestions, objections?

**Comment by christopheschwyzer** [comment]
This could be a _hackathon_ project...
